# Generated by Django 4.0 on 2022-03-27 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Аватар')),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата рождения')),
                ('language', models.TextField(blank=True, max_length=512, null=True, verbose_name='Язык')),
                ('status', models.TextField(blank=True, max_length=512, null=True, verbose_name='Статус')),
                ('purchased_lessonPacks', models.ManyToManyField(blank=True, related_name='profiles', to='courses.LessonPack', verbose_name='Купленные уроки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
