# Generated by Django 4.0.3 on 2022-04-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_delete_completedlesson'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='courses.lesson', verbose_name='Пройденные уроки'),
        ),
    ]
