# Generated by Django 4.0.3 on 2022-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_delete_completedlesson'),
        ('user_profile', '0003_userprofile_lessons_on_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availvable_lessons',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='courses.lesson', verbose_name='Доступные уроки'),
        ),
    ]
