# Generated by Django 4.0.3 on 2022-04-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_availvable_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='availvable_lessons',
            new_name='available_lessons',
        ),
    ]
