# Generated by Django 4.0.3 on 2022-05-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
