# Generated by Django 4.0.3 on 2022-05-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=64, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('m', 'Муж'), ('f', 'Жен'), ('none', '')], default='none', max_length=3, verbose_name='Пол'),
        ),
    ]
