# Generated by Django 4.0.3 on 2022-05-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_userprofile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
    ]
