# Generated by Django 4.0.3 on 2022-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_remove_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('Муж', 'male'), ('Жен', 'female'), ('не указан', 'unset')], default='none', max_length=9, verbose_name='Пол'),
        ),
    ]
