# Generated by Django 4.0.3 on 2022-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_remove_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('Мужcкой', 'Мужcкой'), ('Женский', 'Женский'), ('не указан', 'не указан')], default='не указан', max_length=9, verbose_name='Пол'),
        ),
    ]
