# Generated by Django 4.0.3 on 2022-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_remove_userprofile_status_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language_code',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Фото'),
        ),
    ]
