# Generated by Django 4.0.3 on 2022-06-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_remove_userprofile_language_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='thumbnails', verbose_name='Thumbnail'),
        ),
    ]
