# Generated by Django 4.0.3 on 2022-07-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_userprofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Мужcкой'), ('Female', 'Женский'), ('Unspecified', 'не указан')], default='Unspecified', max_length=11, verbose_name='Пол'),
        ),
    ]
