# Generated by Django 4.0.3 on 2022-05-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
