# Generated by Django 4.0.3 on 2022-04-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lessonstatus_lesson_lessonstatus_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstatus',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='courses.lessonstatus'),
        ),
    ]
