# Generated by Django 4.0.3 on 2022-04-07 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_remove_lesson_status_lesson_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstatus',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lessonstatus',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
    ]
