# Generated by Django 4.0.3 on 2022-04-07 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_remove_lessonstatus_lessons_lessonstatus_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Пройденный урок',
                'verbose_name_plural': 'Пройденные уроки',
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='users',
        ),
        migrations.DeleteModel(
            name='LessonStatus',
        ),
        migrations.AddField(
            model_name='completedlesson',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='completed', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='completedlesson',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
