# Generated by Django 4.0.3 on 2022-04-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_completedlesson_remove_lesson_users_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedLesson',
        ),
    ]
