# Generated by Django 4.0.3 on 2022-05-11 14:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_lesson_excersize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='excersize',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задание'),
        ),
    ]
