# Generated by Django 4.0.3 on 2022-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_voicemessage_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemessage',
            name='blob',
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='file',
            field=models.FileField(null=True, upload_to='voice_messages/'),
        ),
    ]
