# Generated by Django 4.0.3 on 2022-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_voicemessage_blob_voicemessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemessage',
            name='file',
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='blob',
            field=models.BinaryField(null=True),
        ),
    ]
