# Generated by Django 4.0.3 on 2022-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_voicemessage_file_voicemessage_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemessage',
            name='blob',
            field=models.FileField(null=True, upload_to='voice_messages/'),
        ),
    ]
