# Generated by Django 4.0.3 on 2022-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_voicemessage_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voice',
            field=models.FileField(null=True, upload_to='voice_messages/'),
        ),
    ]
