# Generated by Django 4.0.3 on 2022-06-24 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_userprofile_thumbnail'),
        ('courses', '0022_comment_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excersize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'none'), ('onReview', 'onReview'), ('completed', 'completed')], default='none', max_length=9)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excersizes', to='courses.lesson', verbose_name='Урок')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excersizes', to='user_profile.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
