# Generated by Django 4.0.3 on 2022-06-24 05:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_excersizemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='excersize',
        ),
        migrations.AddField(
            model_name='excersize',
            name='excersize_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задание'),
        ),
    ]
