# Generated by Django 4.0.3 on 2022-06-24 07:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_userprofile_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0026_remove_excersize_excersize_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'none'), ('onReview', 'onReview'), ('completed', 'completed')], default='none', max_length=9)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='ReviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=5000, verbose_name='Содержание')),
                ('voice', models.FileField(null=True, upload_to='voice_messages/')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_messages', to='courses.review', verbose_name='Ревью')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение в ревью',
                'verbose_name_plural': 'Сообщения в ревью',
            },
        ),
        migrations.RemoveField(
            model_name='excersize',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='excersize',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='excersize_text',
        ),
        migrations.AddField(
            model_name='excersize',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задание'),
        ),
        migrations.DeleteModel(
            name='ExcersizeMessage',
        ),
        migrations.AddField(
            model_name='review',
            name='excersize',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='courses.excersize', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user_profile.userprofile', verbose_name='Пользователь'),
        ),
    ]
