# Generated by Django 4.0.3 on 2022-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_review_reviewmessage_remove_excersize_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
