# Generated by Django 4.0.3 on 2022-06-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_reviewmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='excersize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.excersize', verbose_name='Задание'),
        ),
    ]
