# Generated by Django 4.0.3 on 2022-07-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_review_excersize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Ревью', 'verbose_name_plural': 'Ревью'},
        ),
        migrations.AddField(
            model_name='reviewmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.reviewmessage', verbose_name='Родитель'),
        ),
    ]
