# Generated by Django 4.0.3 on 2022-07-13 12:13

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_lessonpack_price2_lessonpack_price2_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonpack',
            old_name='price2_currency',
            new_name='price_currency',
        ),
        migrations.RemoveField(
            model_name='lessonpack',
            name='price2',
        ),
        migrations.AlterField(
            model_name='lessonpack',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=14, null=True),
        ),
    ]
