# Generated by Django 4.0.3 on 2022-07-25 06:17

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_rename_price2_currency_lessonpack_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpack',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='RUB', max_digits=14, null=True),
        ),
    ]
