# Generated by Django 4.0.3 on 2022-07-25 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_lessonpack_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessonPack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.lessonpack', verbose_name='Группа уроков'),
        ),
    ]
