# Generated by Django 4.0.3 on 2022-07-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_lesson_lessonpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/comment-images', verbose_name='Изображение'),
        ),
    ]
