# Generated by Django 4.0.3 on 2022-07-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_commentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmessageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/review-images', verbose_name='Изображение'),
        ),
    ]
