# Generated by Django 4.0.3 on 2022-07-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_alter_lesson_lessonpack'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='packRef',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='courses.lessonpack', verbose_name='Референс к товару'),
        ),
    ]
