# Generated by Django 4.0.3 on 2022-07-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cartitem_packref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='packRef',
            new_name='ref',
        ),
    ]
